export const LOGIN_ADMIN_REQUEST = "LOGIN_ADMIN_REQUEST";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS";
export const LOGIN_ADMIN_FAILURE = "LOGIN_ADMIN_FAILURE";

export const ADMIN_AUTH_SUCCESS = "ADMIN_AUTH_SUCCESS";
export const ADMIN_AUTH_FAILURE = "ADMIN_AUTH_FAILURE";

export const LOGOUT_ADMIN_SUCCESS = "LOGOUT_ADMIN_SUCCESS";
export const LOGOUT_ADMIN_FAILURE = "LOGOUT_ADMIN_FAILURE";

export const ADD_STAFF_REQUEST = "ADD_STAFF_REQUEST";
export const ADD_STAFF_SUCCESS = "ADD_STAFF_SUCCESS";
export const ADD_STAFF_FAILURE = "ADD_STAFF_FAILURE";

export const FETCH_STAFF_REQUEST = "FETCH_STAFF_REQUEST";
export const FETCH_STAFF_SUCCESS = "FETCH_STAFF_SUCCESS";
export const FETCH_STAFF_FAILURE = "FETCH_STAFF_FAILURE";

export const REGISTER_STUDENT_SUCCESS = "REGISTER_STUDENT_SUCCESS";
export const REGISTER_STUDENT_REQUEST = "REGISTER_STUDENT_REQUEST";
export const REGISTER_STUDENT_FAILURE = "REGISTER_STUDENT_FAILURE";

export const EMPTY_SUCCESS_MESSAGE = "EMPTY_SUCCESS_MESSAGE";
export const EMPTY_FAILURE_MESSAGE = "EMPTY_FAILURE_MESSAGE";

export const ADD_BATCH_REQUEST = "ADD_BATCH_REQUEST";
export const ADD_BATCH_SUCCESS = "ADD_BATCH_SUCCESS";
export const ADD_BATCH_FAILURE = "ADD_BATCH_FAILURE";

export const FETCH_BATCH_REQUEST = "FETCH_BATCH_REQUEST";
export const FETCH_BATCH_SUCCESS = "FETCH_BATCH_SUCCESS";
export const FETCH_BATCH_FAILURE = "FETCH_BATCH_FAILURE";

export const DELETE_BATCH_REQUEST = "DELETE_BATCH_REQUEST";
export const DELETE_BATCH_SUCCESS = "DELETE_BATCH_SUCCESS";
export const DELETE_BATCH_FAILURE = "DELETE_BATCH_FAILURE";