export const ADD_INCOME_REQUEST = "ADD_INCOME_REQUEST";
export const ADD_INCOME_SUCCESS = "ADD_INCOME_SUCCESS";
export const ADD_INCOME_FAILURE = "ADD_INCOME_FAILURE";

export const GET_INCOME_REQUEST = "GET_INCOME_REQUEST";
export const GET_INCOME_SUCCESS = "GET_INCOME_SUCCESS";
export const GET_INCOME_FAILURE = "GET_INCOME_FAILURE";

export const DELETE_INCOME_REQUEST = "DELETE_INCOME_REQUEST";
export const DELETE_INCOME_SUCCESS = "DELETE_INCOME_SUCCESS";
export const DELETE_INCOME_FAILURE = "DELETE_INCOME_FAILURE";

export const ADD_INSTALLMENT_REQUEST = "ADD_INSTALLMENT_REQUEST";
export const ADD_INSTALLMENT_SUCCESS = "ADD_INSTALLMENT_SUCCESS";
export const ADD_INSTALLMENT_FAILURE = "ADD_INSTALLMENT_FAILURE";

export const EMPTY_INCOME_SUCCESS_MESSAGE = "EMPTY_INCOME_SUCCESS_MESSAGE";
export const EMPTY_INCOME_FAILURE_MESSAGE = "EMPTY_FAILUREINCOME__MESSAGE";